export const colors = {
  background: '#F8FAF6',
  surface: '#FFFFFF',
  primary: '#6B9E7A',
  primaryDark: '#4F7D5E',
  primaryLight: '#E8F2EA',
  sage: '#8FB89A',
  sageLight: '#EDF4EF',
  accent: '#C4B86A',
  accentLight: '#FAF8F0',
  yellow: '#F5EFD9',
  yellowMuted: '#E8DFC4',
  yellowDark: '#9A8548',
  text: '#2C3E2C',
  textMuted: '#7A8F7A',
  border: '#E2EBE2',
  streak: '#C9A84C',
  mic: '#6B9E7A',
  micRecording: '#D96B6B',
  error: '#D96B6B',
  success: '#6B9E7A',
  progressLow: '#D9966B',
  progressMid: '#C9A84C',
  progressHigh: '#6B9E7A',
};

export const cardAccents = [
  { bg: colors.primaryLight, text: colors.primaryDark },
  { bg: colors.yellow, text: colors.yellowDark },
  { bg: colors.sageLight, text: colors.sage },
  { bg: colors.accentLight, text: colors.accent },
  { bg: colors.yellowMuted, text: colors.yellowDark },
];
